vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        concert:
            uri_prefix: /images/concerts
            upload_destination: '%kernel.project_dir%/public/images/concerts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer